--
-- PostgreSQL database dump
--

\restrict OylAUtbPu0tjgU1MSfSfT45SZbBS5EEqBA2mM02o2p2uZgdbzq8TsVKitRHji9z

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: customers_product; Type: TABLE; Schema: public; Owner: zarly_user
--

CREATE TABLE public.customers_product (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    price numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    weight_grams integer NOT NULL,
    image character varying(100),
    is_available boolean NOT NULL,
    category character varying(100) NOT NULL,
    bundle_price numeric(10,2),
    bundle_quantity integer,
    bundle_weight_grams integer,
    is_unlimited_stock boolean NOT NULL,
    bundle_stock integer
);


ALTER TABLE public.customers_product OWNER TO zarly_user;

--
-- Name: customers_product_id_seq; Type: SEQUENCE; Schema: public; Owner: zarly_user
--

ALTER TABLE public.customers_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: customers_product; Type: TABLE DATA; Schema: public; Owner: zarly_user
--

COPY public.customers_product (id, name, price, stock, weight_grams, image, is_available, category, bundle_price, bundle_quantity, bundle_weight_grams, is_unlimited_stock, bundle_stock) FROM stdin;
23	Pisang Nipah	13.00	100	200	\N	t	Pisang	\N	\N	\N	f	\N
25	Pisang Salai Original	12.00	100	300	\N	t	Pisang	\N	\N	\N	f	\N
26	Pisang Salai Bandug	10.00	100	200	\N	t	Pisang	\N	\N	\N	f	\N
41	Kacang Santong	12.00	100	280	\N	t	Kacang	\N	\N	\N	f	\N
48	Kacang Parang Isi	12.00	100	300	\N	t	Kacang	\N	\N	\N	f	\N
49	Kacang Parang Satay	12.00	100	300	\N	t	Kacang	\N	\N	\N	f	\N
50	Kacang Parang Kulit	12.00	100	300	\N	t	Kacang	\N	\N	\N	f	\N
51	Kacang Tanah Kari	12.00	100	300	\N	t	Kacang	\N	\N	\N	f	\N
54	Popia Cheese	20.00	100	300	\N	t	Popia	\N	\N	\N	f	\N
55	Popia Nestum	20.00	100	300	\N	t	Popia	\N	\N	\N	f	\N
56	Popia Susu	20.00	100	300	\N	t	Popia	\N	\N	\N	f	\N
1	Kuih Kapit Berinti Coklat	28.00	100	0	\N	t	Kuih Kapit	307.50	15	0	f	\N
2	Kuih Kapit Berinti Kacang	28.00	100	0	\N	t	Kuih Kapit	300.00	15	0	f	\N
3	Kuih Kapit Berinti Durian	28.00	100	0	\N	t	Kuih Kapit	300.00	15	0	f	\N
4	Ubi Masin	10.00	100	390	\N	t	Ubi	65.00	1	5000	f	\N
5	Ubi Pedas Basah	12.00	100	300	\N	t	Ubi	75.00	1	5000	f	\N
6	Ubi Pedas Kering	12.00	100	300	\N	t	Ubi	72.00	1	5000	f	\N
7	Ubi Cheese	12.00	100	300	\N	t	Ubi	68.00	1	4000	f	\N
8	Ubi Kari	12.00	100	300	\N	t	Ubi	64.00	1	4000	f	\N
9	Ubi Ayam Spicy	12.00	100	300	\N	t	Ubi	68.00	1	4000	f	\N
10	Ubi Keledek Ungu	12.00	100	230	\N	t	Ubi	98.00	1	5000	f	\N
11	Rempeyek Mini	12.00	100	200	\N	t	Rempeyek	102.00	1	5000	f	\N
12	Kentang Kari	12.00	100	280	\N	t	Kentang	48.00	1	2500	f	\N
13	Kentang Lemak	10.00	100	300	\N	t	Kentang	39.00	1	2500	f	\N
14	Kentang Ayam Spicy	10.00	100	280	\N	t	Kentang	48.00	1	2500	f	\N
15	K. Kacang Hijau	10.00	100	280	\N	t	Kentang	45.00	1	2000	f	\N
16	Roda Ayam Spicy	10.00	100	280	\N	t	Roda	48.00	1	3000	f	\N
17	Roda Original	10.00	100	300	\N	t	Roda	39.00	1	2500	f	\N
18	Roda Cheese	10.00	100	280	\N	t	Roda	48.00	1	3000	f	\N
19	Maruku Campur	10.00	100	380	\N	t	Maruku	62.00	1	5000	f	\N
20	Maruku Leper	10.00	100	380	\N	t	Maruku	62.00	1	5000	f	\N
21	Maruku Sedang	10.00	100	380	\N	t	Maruku	62.00	1	5000	f	\N
22	Maruku Star	10.00	100	380	\N	t	Maruku	62.00	1	5000	f	\N
24	Pisang Manis	15.00	100	285	\N	t	Pisang	120.00	1	5000	f	\N
27	Pisang Tanduk	13.00	100	200	\N	t	Pisang	185.00	1	5000	f	\N
28	Onion Ring	10.00	100	280	\N	t	Lain-lain	50.00	1	2500	f	\N
29	Bika Kari	10.00	100	300	\N	t	Lain-lain	70.00	1	5000	f	\N
32	Mee Siput	10.00	100	280	\N	t	Lain-lain	85.00	1	5000	f	\N
33	Tempe Bulat	12.00	100	260	\N	t	Lain-lain	95.00	1	5000	f	\N
34	Tortila	10.00	100	200	\N	t	Lain-lain	45.00	1	2000	f	\N
35	Popia Udang	20.00	100	350	\N	t	Popia	180.00	1	5000	f	\N
36	Serunding Daging	12.00	100	100	\N	t	Serunding	75.00	1	1000	f	\N
37	Serunding Ayam	12.00	100	100	\N	t	Serunding	78.00	1	1000	f	\N
38	Kacang Pilus Ori	12.00	100	230	\N	t	Kacang	88.00	1	5000	f	\N
39	Kacang Pilus Spicy	12.00	100	230	\N	t	Kacang	88.00	1	5000	f	\N
57	Rempeyek Original	23.00	100	0	\N	t	Rempeyek	195.00	10	0	f	\N
58	Rempeyek Spicy	23.00	100	0	\N	t	Rempeyek	195.00	10	0	f	\N
59	Rempeyek Kacang Hijau	23.00	100	0	\N	t	Rempeyek	195.00	10	0	f	\N
60	Rempeyek Kacang Dall	23.00	100	0	\N	t	Rempeyek	195.00	10	0	f	\N
31	Bawang	10.00	1	370		t	Bawang	70.00	1	5000	f	\N
40	Kacang Hijau Masin	12.00	12	300		t	Kacang	\N	\N	\N	f	\N
43	Kacang Gulabi	12.00	6	280		t	Kacang	\N	\N	\N	f	\N
47	Kacang Botak Kuning	12.00	21	300		t	Kacang	\N	\N	\N	f	\N
46	Kacang Hijau Kari	12.00	12	350		t	Kacang	\N	\N	\N	f	\N
53	Kacang Kuda	12.00	5	280		t	Kacang	\N	\N	\N	f	\N
45	Kacang Campur	12.00	1	350		t	Kacang	\N	\N	\N	f	\N
42	Kacang Hai Kuning	12.00	1	350		t	Kacang	\N	\N	\N	f	\N
52	Kacang Medan	12.00	9	300		t	Kacang	\N	\N	\N	f	\N
44	Kacang Hijau Jepun	12.00	9	300		t	Kacang	\N	\N	\N	f	\N
30	Bawang Kampung	10.00	20	250		t	Bawang	87.00	1	5000	f	\N
\.


--
-- Name: customers_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zarly_user
--

SELECT pg_catalog.setval('public.customers_product_id_seq', 60, true);


--
-- Name: customers_product customers_product_pkey; Type: CONSTRAINT; Schema: public; Owner: zarly_user
--

ALTER TABLE ONLY public.customers_product
    ADD CONSTRAINT customers_product_pkey PRIMARY KEY (id);


--
-- Name: customers_product_is_available_33c677eb; Type: INDEX; Schema: public; Owner: zarly_user
--

CREATE INDEX customers_product_is_available_33c677eb ON public.customers_product USING btree (is_available);


--
-- PostgreSQL database dump complete
--

\unrestrict OylAUtbPu0tjgU1MSfSfT45SZbBS5EEqBA2mM02o2p2uZgdbzq8TsVKitRHji9z

