# Generated by Django 6.0.1 on 2026-01-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_payment', 'Approved but pending payment')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_hash', models.CharField(max_length=64)),
                ('pdf_path', models.FileField(upload_to='signed_pdfs/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signature_value', models.TextField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signature', to='admins.order')),
            ],
        ),
        migrations.DeleteModel(
            name='SignedDocument',
        ),
    ]
