# Generated by Django 6.0.1 on 2026-04-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_order_full_name_order_order_notes_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='action_taken',
            field=models.CharField(blank=True, choices=[('refund', 'Contact User for Refund'), ('remake', 'Remake Order'), ('dismissed', 'Dismiss Complaint')], max_length=50, null=True),
        ),
    ]
