# Generated by Django 6.0.1 on 2026-04-18 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_alter_order_street_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prepared_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['sales_admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('prepared', 'Prepared'), ('rejected', 'Rejected'), ('pending_payment', 'Approved but pending payment')], default='pending', max_length=50),
        ),
    ]
