# Generated by Django 6.0.1 on 2026-04-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_order_prepared_at_order_prepared_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['sales_admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prep_groups', to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(related_name='prep_groups', to='admins.order')),
            ],
        ),
    ]
