# Generated by Django 6.0.1 on 2026-04-18 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_prepgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_assigned_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['sales_admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_for_delivery_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['sales_admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_for_delivery_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('prepared', 'Prepared'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('pending_payment', 'Approved but pending payment')], default='pending', max_length=50),
        ),
    ]
