# Generated by Django 6.0.1 on 2026-04-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_order_courier_name_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe Card Payment'), ('manual', 'Manual Proof (Bank Transfer / DuitNow)'), ('cash', 'Cash on Delivery')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Payment Initiated'), ('processing', 'Payment Processing'), ('succeeded', 'Payment Succeeded'), ('failed', 'Payment Failed'), ('cancelled', 'Payment Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('last_webhook_event', models.CharField(blank=True, max_length=100, null=True)),
                ('webhook_event_timestamp', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admins.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='admins_paym_order_i_b23e78_idx'), models.Index(fields=['status', 'created_at'], name='admins_paym_status_3bbf52_idx'), models.Index(fields=['stripe_session_id'], name='admins_paym_stripe__97988d_idx'), models.Index(fields=['stripe_payment_intent_id'], name='admins_paym_stripe__d91943_idx')],
            },
        ),
    ]
