# Generated by Django 6.0.1 on 2026-05-09 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('reason_text', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('system', 'System Error'), ('customer', 'Customer Issue'), ('payment', 'Payment Issue'), ('inventory', 'Inventory Issue'), ('address', 'Address Issue'), ('other', 'Other')], default='other', max_length=20)),
                ('customer_message', models.TextField(help_text='Message shown to customer')),
                ('internal_note', models.TextField(blank=True, help_text='Internal note for admins only')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Rejection Reasons',
                'ordering': ['category', 'reason_text'],
            },
        ),
        migrations.CreateModel(
            name='RejectedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_reason', models.TextField(blank=True, help_text='Custom rejection reason if admin typed instead of selecting predefined')),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('order_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_item_count', models.PositiveIntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('can_appeal', models.BooleanField(default=True)),
                ('appeal_requested', models.BooleanField(default=False)),
                ('appeal_requested_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_notes', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_record', to='admins.order')),
                ('rejected_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['sales_admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_orders', to=settings.AUTH_USER_MODEL)),
                ('rejection_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.rejectionreason')),
            ],
            options={
                'ordering': ['-rejected_at'],
                'indexes': [models.Index(fields=['order', '-rejected_at'], name='admins_reje_order_i_0083e3_idx'), models.Index(fields=['rejection_reason', 'rejected_at'], name='admins_reje_rejecti_6dc2cd_idx'), models.Index(fields=['customer_email', '-rejected_at'], name='admins_reje_custome_02f990_idx')],
            },
        ),
    ]
