# Generated by Django 6.0.1 on 2026-05-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_rejectionreason_rejectedorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalsignature',
            name='signature_value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
