# Generated by Django 6.0.1 on 2026-05-13 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_signature_value_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_prepared', 'Order Prepared'), ('order_ready_for_delivery', 'Marked Ready for Delivery'), ('order_out_for_delivery', 'Marked Out for Delivery'), ('order_delivered', 'Order Delivered'), ('payment_initiated', 'Payment Initiated'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected'), ('payment_proof_uploaded', 'Payment Proof Uploaded'), ('signature_created', 'Digital Signature Created'), ('receipt_verified', 'Receipt Verification Performed'), ('complaint_submitted', 'Complaint Submitted'), ('complaint_resolved', 'Complaint Resolved'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('tracking_updated', 'Tracking Number Updated'), ('inventory_updated', 'Inventory Updated'), ('product_added', 'Product Added')], db_index=True, max_length=50)),
                ('target_model', models.CharField(blank=True, help_text="e.g., 'Order', 'Payment', 'Complaint'", max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='admins_audi_actor_i_d32fef_idx'), models.Index(fields=['action_type', '-timestamp'], name='admins_audi_action__a2e9fd_idx'), models.Index(fields=['target_model', 'target_id'], name='admins_audi_target__49b433_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Optional URL to navigate to when clicked', max_length=500)),
                ('notification_type', models.CharField(choices=[('order_update', 'Order Update'), ('payment', 'Payment'), ('delivery', 'Delivery'), ('complaint', 'Complaint'), ('admin_alert', 'Admin Alert'), ('system', 'System')], default='system', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='admins_noti_recipie_eaa333_idx')],
            },
        ),
    ]
