# Generated by Django 6.0.1 on 2026-05-14 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_alter_auditlog_action_type_emailtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_proof',
        ),
        migrations.RemoveField(
            model_name='prepgroup',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='prepgroup',
            name='total_orders',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_prepared', 'Order Prepared'), ('order_ready_for_delivery', 'Marked Ready for Delivery'), ('order_out_for_delivery', 'Marked Out for Delivery'), ('order_delivered', 'Order Delivered'), ('payment_initiated', 'Payment Initiated'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected'), ('payment_proof_uploaded', 'Payment Proof Uploaded'), ('signature_created', 'Digital Signature Created'), ('receipt_verified', 'Receipt Verification Performed'), ('complaint_submitted', 'Complaint Submitted'), ('complaint_resolved', 'Complaint Resolved'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('tracking_updated', 'Tracking Number Updated'), ('inventory_updated', 'Inventory Updated'), ('product_added', 'Product Added'), ('refund_issued', 'Refund Issued'), ('refund_failed', 'Refund Failed'), ('refund_manual', 'Manual Refund Flagged'), ('refund_processed', 'Manual Refund Processed'), ('order_cancelled', 'Order Cancelled by Customer')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('prepared', 'Prepared'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by Customer'), ('pending_payment', 'Approved but pending payment')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='refund',
            name='source',
            field=models.CharField(choices=[('order_rejection', 'Order Rejection'), ('complaint', 'Customer Complaint'), ('customer_cancellation', 'Customer Cancellation'), ('webhook', 'Stripe Webhook')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rejectedorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rejection_record', to='admins.order'),
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('prepared', 'Prepared'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by Customer'), ('pending_payment', 'Approved but pending payment')], max_length=50)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='admins.order')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['order', 'status'], name='admins_orde_order_i_02d4cb_idx'), models.Index(fields=['order', '-timestamp'], name='admins_orde_order_i_cfbaf3_idx')],
            },
        ),
    ]
