# Generated by Django 6.0.1 on 2026-05-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0019_remove_order_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
    ]
