# Generated by Django 6.0.1 on 2026-05-14 14:03

import hashlib
import json
from django.db import migrations, models


GENESIS = 'ZARLY_AUDIT_CHAIN_V1'


def backfill_chain(apps, schema_editor):
    AuditLog = apps.get_model('admins', 'AuditLog')
    prev_hash = hashlib.sha256(GENESIS.encode()).hexdigest()

    entries = list(AuditLog.objects.order_by('id'))
    for entry in entries:
        content = '|'.join([
            prev_hash,
            str(entry.actor_id or ''),
            entry.action_type,
            entry.description,
            entry.target_model,
            str(entry.target_id or ''),
            json.dumps(entry.metadata, sort_keys=True),
            entry.ip_address or '',
        ])
        entry.chain_hash = hashlib.sha256(content.encode('utf-8')).hexdigest()
        prev_hash = entry.chain_hash

    AuditLog.objects.bulk_update(entries, ['chain_hash'])


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0020_walk_in_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='chain_hash',
            field=models.CharField(blank=True, db_index=True, help_text="SHA-256 of this entry's content chained with the previous entry's hash.", max_length=64),
        ),
        migrations.RunPython(backfill_chain, migrations.RunPython.noop),
    ]
