# Generated by Django 6.0.1 on 2026-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0021_auditlog_chain_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
