# Generated by Django 6.0.1 on 2026-05-16 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0022_complaint_resolution_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='admins_paym_stripe__97988d_idx',
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='admins_comp_status_e5c8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['order', 'status'], name='admins_comp_order_i_3a8d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='admins_orde_status_46f25c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='admins_orde_status_57124d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='admins_orde_custome_b83cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_priority', 'status'], name='admins_orde_is_prio_cb934a_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order', '-created_at'], name='admins_refu_order_i_116ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', '-created_at'], name='admins_refu_status_8449f7_idx'),
        ),
    ]
