# Generated by Django 6.0.1 on 2026-05-17 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0023_db_indexes_and_perf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_prepared', 'Order Prepared'), ('order_ready_for_delivery', 'Marked Ready for Delivery'), ('order_out_for_delivery', 'Marked Out for Delivery'), ('order_delivered', 'Order Delivered'), ('payment_initiated', 'Payment Initiated'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected'), ('payment_proof_uploaded', 'Payment Proof Uploaded'), ('signature_created', 'Digital Signature Created'), ('receipt_verified', 'Receipt Verification Performed'), ('complaint_submitted', 'Complaint Submitted'), ('complaint_resolved', 'Complaint Resolved'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('tracking_updated', 'Tracking Number Updated'), ('inventory_updated', 'Inventory Updated'), ('product_added', 'Product Added'), ('refund_issued', 'Refund Issued'), ('refund_failed', 'Refund Failed'), ('refund_manual', 'Manual Refund Flagged'), ('refund_processed', 'Manual Refund Processed'), ('order_cancelled', 'Order Cancelled by Customer'), ('support_message_sent', 'Support Message Sent')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(default=False)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='admins.complaint')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['complaint', 'created_at'], name='admins_supp_complai_a0e05b_idx')],
            },
        ),
    ]
