# Generated by Django 6.0.1 on 2026-05-18 17:10

import admins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0026_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to=admins.models.upload_payment_proof_to),
        ),
    ]
