# Generated by Django 6.0.1 on 2026-06-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0035_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_commitment_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_confirmed_by_customer', 'Order Confirmed by Customer (OTP)'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_prepared', 'Order Prepared'), ('order_ready_for_delivery', 'Marked Ready for Delivery'), ('order_out_for_delivery', 'Marked Out for Delivery'), ('order_delivered', 'Order Delivered'), ('payment_initiated', 'Payment Initiated'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected'), ('payment_proof_uploaded', 'Payment Proof Uploaded'), ('signature_created', 'Digital Signature Created'), ('receipt_verified', 'Receipt Verification Performed'), ('complaint_submitted', 'Complaint Submitted'), ('complaint_resolved', 'Complaint Resolved'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('tracking_updated', 'Tracking Number Updated'), ('inventory_updated', 'Inventory Updated'), ('product_added', 'Product Added'), ('refund_issued', 'Refund Issued'), ('refund_failed', 'Refund Failed'), ('refund_manual', 'Manual Refund Flagged'), ('refund_processed', 'Manual Refund Processed'), ('order_cancelled', 'Order Cancelled by Customer'), ('support_message_sent', 'Support Message Sent'), ('product_edited', 'Product Edited'), ('product_deleted', 'Product Deleted'), ('product_availability_toggled', 'Product Availability Toggled'), ('customer_signup', 'Customer Signup'), ('email_verified', 'Email Verified'), ('password_reset', 'Password Reset via OTP'), ('password_changed', 'Password Changed via OTP'), ('account_deleted', 'Account Self-Deleted'), ('login_rate_limited', 'Login Rate Limited'), ('order_approved_unpaid', 'Order Approved (Collect on Delivery)'), ('campaign_sent', 'Campaign Sent'), ('email_template_created', 'Email Template Created'), ('order_stepped_back', 'Order Stepped Back'), ('marketing_opt_out', 'Marketing Opt-Out (Unsubscribe)')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'Pending Customer Confirmation'), ('pending', 'Pending'), ('approved', 'Approved'), ('prepared', 'Prepared'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by Customer'), ('pending_payment', 'Approved but pending payment')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'Pending Customer Confirmation'), ('pending', 'Pending'), ('approved', 'Approved'), ('prepared', 'Prepared'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by Customer'), ('pending_payment', 'Approved but pending payment')], max_length=50),
        ),
    ]
