# Generated by Django 6.0.1 on 2026-04-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_allergy_category_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('sales_admin', 'Sales Administrator'), ('manager', 'Manager')], default='customer', max_length=50, null=True),
        ),
    ]
