# Generated by Django 6.0.1 on 2026-04-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_corporate_whitelisted',
            field=models.BooleanField(default=False, help_text='Whitelisted corporate customers get auto-approval for orders'),
        ),
    ]
