# Generated by Django 6.0.1 on 2026-04-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_user_is_corporate_whitelisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_corporate_whitelisted',
        ),
    ]
