# Generated by Django 6.0.1 on 2026-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='VIP/priority customer flag — surfaces orders at top of queue'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
