# Generated by Django 6.0.1 on 2026-05-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_favourite_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('sales_admin', 'Sales Administrator'), ('manager', 'Manager')], db_index=True, default='customer', max_length=50, null=True),
        ),
    ]
