# Generated by Django 6.0.1 on 2026-05-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_orderrating_productreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderrating',
            new_name='customers_o_custome_7087fa_idx',
            old_name='customers_orderrating_customer_idx',
        ),
        migrations.RenameIndex(
            model_name='productreview',
            new_name='customers_p_product_37dc52_idx',
            old_name='customers_productreview_product_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
