"""
Django settings for zarlyOs project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os 
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file.
# override=True ensures the project .env wins over stale system variables.
load_dotenv(os.path.join(BASE_DIR, '.env'), override=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    f'https://{h}' for h in ALLOWED_HOSTS if not h.startswith('.')
] + [
    f'http://{h}' for h in ALLOWED_HOSTS if not h.startswith('.')
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'customers',
    'admins',
    'django_bootstrap5',
    'django_ratelimit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'zarlyOs.middleware.EagerNonceCSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'zarlyOs.middleware.SessionTimeoutMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admins.middleware.PageViewMiddleware',
]

ROOT_URLCONF = 'zarlyOs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # points to root templates/
        'APP_DIRS': True,  # Keep this True for flexibility
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'admins.context_processors.unread_notifications',
                'customers.context_processors.cart_context',
                'csp.context_processors.nonce',
            ],
        },
    },
]

WSGI_APPLICATION = 'zarlyOs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DATABASE_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DATABASE_NAME', 'zarlydb'),
        'USER': os.getenv('DATABASE_USER', 'zarlyuser'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', 'zarlypass123'),
        'HOST': os.getenv('DATABASE_HOST', 'localhost'),
        'PORT': os.getenv('DATABASE_PORT', '5432'),
        'CONN_MAX_AGE': 60,
    }
}

# Upload and field limits — prevent parser-flooding via large POST bodies or field counts
DATA_UPLOAD_MAX_MEMORY_SIZE  = 5 * 1024 * 1024   # 5 MB (matches payment proof cap)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100               # default 1000 is too permissive
FILE_UPLOAD_MAX_MEMORY_SIZE  = 5 * 1024 * 1024   # 5 MB


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'                     # URL prefix when serving files
STATICFILES_DIRS = [                        # Where Django looks for your own static files
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# use own cutom user model, bukan default
AUTH_USER_MODEL = 'customers.User'

# setting utk authentication
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'product_list' # Will use our home_redirect function
LOGOUT_REDIRECT_URL = 'product_list'

# ============================================================================
# STRIPE CONFIGURATION
# ============================================================================
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')
STRIPE_CURRENCY = os.getenv('STRIPE_CURRENCY', 'MYR')

# For localhost testing: use ngrok or Stripe CLI to tunnel webhooks
# Stripe CLI: stripe listen --forward-to localhost:8000/menu/stripe/webhook/
STRIPE_WEBHOOK_TOLERANCE = 300  # Accept webhooks within 5 minutes of creation

# ============================================================================
# EMAIL
# ============================================================================
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@zarlybigfood.com')

# ============================================================================
# SUPPORT CHAT
# ============================================================================
# Fernet 32-byte URL-safe base64 key. Generate once with:
# python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
SUPPORT_CHAT_KEY = os.getenv('SUPPORT_CHAT_KEY', '')

# ============================================================================
# CACHE (django-ratelimit + session storage)
#
# Production: set REDIS_URL=redis://:<password>@<host>:6379/0 in .env
#   pip install django-redis
#
# Development: leave REDIS_URL unset — falls back to LocMemCache (single-worker only).
# ============================================================================
_REDIS_URL = os.getenv('REDIS_URL', '')

if _REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': _REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                # Degrade gracefully on Redis unavailability rather than 500-ing
                'IGNORE_EXCEPTIONS': True,
            },
            'KEY_PREFIX': 'zarly',
        }
    }
else:
    # Dev / single-worker fallback — ratelimit counts are not shared across workers
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }
    # Silence ratelimit's strict backend check for local dev only
    SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003', 'django_ratelimit.W001']

# ============================================================================
# SECURITY HEADERS
# ============================================================================
SECURE_CONTENT_TYPE_NOSNIFF = True      # X-Content-Type-Options: nosniff
X_FRAME_OPTIONS = 'DENY'                # Clickjacking protection
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SESSION_COOKIE_HTTPONLY = True          # Block JS access to session cookie
CSRF_COOKIE_HTTPONLY = True             # Block JS access to CSRF cookie

# ============================================================================
# SESSION EXPIRY
# ============================================================================
# Sessions expire 1 hour after the last request (inactivity-based, not absolute).
# SESSION_SAVE_EVERY_REQUEST resets the cookie expiry on every request so the
# clock only counts down during genuine inactivity.
# SessionTimeoutMiddleware enforces the same limit server-side regardless of
# whether the client honours the cookie max-age.
#
# Expired session rows accumulate in the DB — clean them up periodically:
#   python manage.py clearsessions
# (add to cron: 0 * * * *  cd /app && python manage.py clearsessions)
SESSION_COOKIE_AGE = 3600              # Cookie max-age: 1 hour
SESSION_SAVE_EVERY_REQUEST = True      # Refresh expiry on every request
SESSION_INACTIVITY_TIMEOUT = 3600      # Server-side inactivity limit (seconds)

# Enable these in production (HTTPS required):
# SECURE_SSL_REDIRECT = not DEBUG
# SESSION_COOKIE_SECURE = not DEBUG
# CSRF_COOKIE_SECURE = not DEBUG
# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# ============================================================================
# CONTENT SECURITY POLICY
# ============================================================================
# script-src uses per-request nonces — inline scripts must carry
# nonce="{{ request.csp_nonce }}" to execute. Injected scripts are blocked.
CSP_DEFAULT_SRC  = ("'self'",)
CSP_SCRIPT_SRC   = ("'self'", "https://cdn.jsdelivr.net", "https://unpkg.com")
CSP_STYLE_SRC    = (
    "'self'", "'unsafe-inline'",
    "https://cdn.jsdelivr.net",
    "https://unpkg.com",
    "https://fonts.googleapis.com",
)
CSP_FONT_SRC     = ("'self'", "https://fonts.gstatic.com")
CSP_IMG_SRC      = ("'self'", "data:", "blob:")
CSP_CONNECT_SRC  = ("'self'", "https://nominatim.openstreetmap.org", "https://unpkg.com")
CSP_FRAME_ANCESTORS = ("'none'",)
CSP_OBJECT_SRC   = ("'none'",)
CSP_BASE_URI     = ("'self'",)
CSP_FORM_ACTION  = ("'self'",)
CSP_INCLUDE_NONCE_IN = ["script-src"]
